# Generated by Django 4.2.5 on 2023-10-01 19:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("App_One", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Usuarios",
            new_name="Usuario",
        ),
    ]
